#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# extract_endpoints.sh
#
# Reads every lmsa_*_urls.txt file in the repository, extracts unique
# download endpoints (base hosts and directory-level paths), and writes
# a summarised report to endpoints.txt.
#
# Usage:
#   ./extract_endpoints.sh [output_file]
#
# Default output: endpoints.txt (in the same directory as this script)
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${1:-${SCRIPT_DIR}/endpoints.txt}"

URL_FILES=(
  "${SCRIPT_DIR}/lmsa_tool_urls.txt"
  "${SCRIPT_DIR}/lmsa_rom_urls.txt"
  "${SCRIPT_DIR}/lmsa_firmware_urls.txt"
  "${SCRIPT_DIR}/lmsa_other_urls.txt"
  "${SCRIPT_DIR}/lmsa_plugin_urls.txt"
)

# ── Collect every URL (first field, tab-separated) ──────────────────
collect_urls() {
  for f in "${URL_FILES[@]}"; do
    [ -f "$f" ] && cut -f1 "$f"
  done
}

# ── Extract scheme://host from a URL ────────────────────────────────
extract_host() {
  # Strips path + query; keeps scheme://hostname
  sed -E 's|^(https?://[^/?]+).*|\1|'
}

# ── Extract the directory-level endpoint (path without filename) ────
extract_path_endpoint() {
  # 1. Remove query string (?…)
  # 2. Remove the last path component (the filename)
  # 3. Append trailing /
  sed -E 's|\?.*||; s|/[^/]*$||; s|$|/|'
}

# ── Main ─────────────────────────────────────────────────────────────
all_urls="$(collect_urls)"
total="$(echo "$all_urls" | grep -c .)"

# Unique base hosts
hosts="$(echo "$all_urls" | extract_host | sort -u)"

# Unique directory-level endpoints (scheme + host + dir path)
endpoints="$(echo "$all_urls" | extract_path_endpoint | sort -u)"

# Count per host (match on "host/" to avoid substring overlaps)
declare -A host_counts
while IFS= read -r host; do
  count="$(echo "$all_urls" | grep -cF "${host}/" || true)"
  host_counts["$host"]="$count"
done <<< "$hosts"

# ── Write report ─────────────────────────────────────────────────────
{
  echo "# Download URL Endpoints"
  echo "#"
  echo "# Auto-generated by extract_endpoints.sh"
  echo "# Date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo "# Total URLs analysed: ${total}"
  echo ""

  echo "## Base Hosts"
  echo ""
  while IFS= read -r host; do
    printf "%-65s  (%s URLs)\n" "$host" "${host_counts[$host]}"
  done <<< "$hosts"

  echo ""
  echo "## Endpoints (unique directory-level paths)"
  echo ""
  echo "$endpoints"
} > "$OUTPUT"

echo "✅  Extracted $(echo "$hosts" | wc -l | tr -d ' ') hosts and $(echo "$endpoints" | wc -l | tr -d ' ') endpoints from ${total} URLs → ${OUTPUT}"
