[Selection]
SelectProduct=PAC_s9863a1h10

[Options]
Repartition=1
Reset=1
FlashPageType=0
EraseAll=0
KeepCharge=0
DDRCheck=0
PowerOff=0
ReadChipUID=0
CheckMatch=0

[Settings]
;If this value is Zero, download complete will be finished
;otherwise (not zero), download complete will wait for this vale (ms),
;and restart download automatically 
WaitTimeForNextChip=0

CheckDriverVer = 1

[Serial port]
Port=0
Baud rate=115200

[NV]
;save to the folder "NVBackup" under the tool folder.
SaveToLocalFlag=0
;Using SN to name nv file,default using IMEI 
;0, use IMEI; 1, use SN
FileNameWithSN=0

[Report]
;report file name is download_result.txt under the tool folder.
enable= 0
;0, Normal; 1, Press; 2, SoftSim
Type = 0
;DUTID: 0, IMEI; 1, SN; 2, ChipUID
DUTID=0

[GUI]
BaudRates= 57600,115200,230400,460800,921600
FileFilter= All file(*.*)|*.*|Image file (*.bin;*.img)|*.bin;*.img||
CanEdit = 1
CanSelect = 1
ScriptControl = 0
MarkLastState = 0
ShowFailedMsgBox = 0
;this flag is only for USB to close port when download complete
;USB and UART is disguised as following:
;before click on start, the port already exists, it will be regarded as UART
;after click on start, the port appeared will be regarded as USB
ClosePortFlag = 0
;EraseAllFlashMsg=You have selected [Erase All Flash], this will clear all data stored in the flash including calibration.IMEI will be erased too and need to be rewritten,If continue?
;EraseIMEIMsg=You have not selected to backup IMEI item,IMEI will be erased and need to be rewritten,If continue?

CmdPackage = 0
PacketMode=1
;Show PAC File path in the title bar
ShowPacPath=0
PowerManageFlag=0
InDLProcess = 1
PowerManageInterval = 10
;Title=研发下载专用

;Show curity tips 0, hide; 1, show;
ShowSecurityTips=0
SafetyTipsMsg=系统更新存在安全风险，请确认是否继续？

[PortSetting]
FilterPort=1,2
EnableFilter = 1
;FixPort option can specify ports to download,format as FixPort=32,46
;HoundType : 0,SetupAPI; 1,WMI; 2,SetupAPI+WMI

[ChipDspMap]
enable = 0

[ReadFlash]
flash00=0:l_fixnv1:0x200000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\sharkl3_pubcp_nvitem.bin
flash01=0:prodnv:0x500000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\prodnv.img
flash02=0:miscdata:0x100000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\miscdata.bin
flash03=0:splloader:0xFFFFFFFF:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\u-boot-spl-16k-sign.bin
flash04=0:vbmeta:0x100000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\vbmeta-sign.img
flash05=0:l_modem:0x1900000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\SC9600_sharkl3_pubcp_modem.dat
flash06=0:l_deltanv:0x100000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\sharkl3_pubcp_deltanv.bin
flash07=0:l_ldsp:0x1400000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\sharkl3_pubcp_LTEA_DSP.bin
flash08=0:l_gdsp:0xA00000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\sharkl3_pubcp_DM_DSP.bin
flash09=0:pm_sys:0x100000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\sharkl3_cm4.bin
flash10=0:gpsgl:0x100000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\gnssmodem.bin
flash11=0:gpsbd:0x100000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\gnssbdmodem.bin
flash12=0:wcnmodem:0xA00000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\PM_sharkl3_cm4.bin
flash13=0:boot:0x2300000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\boot.img
flash14=0:dtb:0x800000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\dtb.img
flash15=0:dtbo:0x800000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\dtbo.img
flash16=0:recovery:0x2800000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\recovery.img
flash17=0:system:0xFFA00000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\system.img
flash18=0:userdata:0xFFFFFFFF:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\userdata.img
flash19=0:logo:0x300000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\LOGO.bmp
flash20=0:fbootlogo:0x300000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\LOGO.bmp(1)
flash21=0:cache:0x9600000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\cache.img
flash22=0:trustos:0x600000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\tos-sign.bin
flash23=0:sml:0x100000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\sml-sign.bin
flash24=0:vendor:0x19000000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\vendor.img
flash25=0:product:0x6400000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\product.img
flash26=0:persist:0x200000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\persist.img
flash27=0:uboot:0x100000:E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ReadFlash\u-boot-sign.bin

[EraseFlash]
;
[WriteFlash]
;

[Download_Packet]
UnpacketDir= .\
packet=E:\Tools\DFS\AK47\SW\LENOVO_AK47_V04_20200107\LENOVO_AK47_V04_20200107.pac
;ShowConfirmDialog,1: Show prompted whether load latest pac file.
ShowConfirmDialog=1


[SN]
NeedPhaseCheck=0
SN_LENGTH = 14
WithDataTime=0
AutoStartAfterInputSN = 1
AutoGenerateSN=1
;FixedSN: set a fixed SN. default is AutoGenerateSN,if length of FixedSN is less than SN_LENGTH, tool will auto padding. if length of FixedSN is greater than SN_LENGTH, Automatically intercept the proper length

[UsageStatistics]
Exsrv = \\10.0.3.44\phone
Insrv =

[Debug]
EnableDebugMode =0
;Data : Enable debug string data

[SC8800G]
FDL=1@
FDL2=1@
NV=1@
BootLoader=1@
KernelImg2=1@
UserImg=1@
MMIRes=1@
SPLOAD=0@
DSPCode=1@
OmadmFota=1@
Preload=1@
RomDisk=0@
FLASH=1@
EraseDU=1@
PhaseCheck=1@
KernelImg=1@

[NOR_FLASH_6600L]
FDL=1@
NV=1@
PS=1@
MMIRes=1@
EraseUdisk=1@
UDISK=0@
FLASH=1@
PhaseCheck=1@

[NOR_FLASH_6610]
FDL=1@
NV=1@
BootLoader=1@
PS=1@
MMIRes=1@
EraseUdisk=1@
UDISK=1@
FLASH=1@
PhaseCheck=1@

[6610_SIM_LOCK]
Init=1@
NV=1@
PS=1@
MMIRes=1@
EraseUdisk=1@
UDISK=1@
FLASH=1@
PhaseCheck=1@

[LTE_SC8800G]
FDL=1@
FDL2=1@
NV=1@
BootLoader=1@
KernelImg2=1@
UserImg=1@
MMIRes=1@
DSPCode=1@
OmadmFota=1@
Preload=1@
RomDisk=0@
FLASH=1@
EraseDU=1@
PhaseCheck=1@
KernelImg=1@

[SC8810_MODEM]
FDL=1@
FDL2=1@
NV=1@
BootLoader=1@
KernelImg2=1@
UserImg=1@
MMIRes=0@
DSPCode=1@
OmadmFota=1@
Preload=0@
RomDisk=0@
FLASH=1@
EraseDU=1@
PhaseCheck=1@
KernelImg=1@

[SC8810]
FDL=1@
FDL2=1@
NV=1@
EraseUBOOT=1@
SPLLoader=1@
UBOOTLoader=1@
Vmjaluna=1@
Modem=1@
DSP=1@
BootImg=1@
Recovery=1@
System=1@
UserData=1@
Boot_Logo=1@
Fastboot_Logo=0@
FLASH=1@
EraseProdEng=1@
PhaseCheck=1@
Cache=1@
EraseMisc=1@

[SC6820]
FDL=1@
FDL2=1@
NV=1@
EraseUBOOT=1@
SPLLoader=1@
UBOOTLoader=1@
Vmjaluna=1@
Modem=1@
DSP=1@
BootImg=1@
Recovery=1@
System=1@
UserData=1@
Boot_Logo=1@
Fastboot_Logo=0@
FLASH=1@
PhaseCheck=1@
EraseCache=1@
EraseMisc=1@

[NOR_FLASH_SC6530]
FDL=1@
NV=1@
PS=1@
MMIRes=1@
EraseUdisk=1@
UDISK=0@
FLASH=1@
PhaseCheck=1@

[SC7702]
FDL=1@
FDL2=1@
NV=1@
BootLoader=1@
KernelImg=1@
DSPCode=1@
ControlData=0@
RomDisk=0@
FLASH=1@
PhaseCheck=1@
RESTAUTODOWNFLAG=1@

[SC8501C]
FDL=1@
FDL2=1@
NV=1@
BootLoader=1@
UserImg=1@
MMIRes=1@
SPLOAD=0@
DSPCode=1@
OmadmFota=0@
FormatFS=1@
FormatHFS=1@
Preload=0@
RomDisk=0@
FLASH=1@
EraseDU=1@
PhaseCheck=1@
KernelImg=1@

[STINGRAY]
FDL=1@
FDL2=1@
NV=1@
EraseUBOOT=1@
SPLLoader=1@
UBOOTLoader=1@
Vmjaluna=1@
Modem=1@
DSP=1@
BootImg=1@
Recovery=1@
System=1@
UserData=1@
Boot_Logo=1@
Fastboot_Logo=0@
FLASH=1@
EraseProdEng=1@
PhaseCheck=1@
Cache=1@
EraseMisc=1@

[SC65XX_MODEM]
FDL=1@
Bootloader=0@
NV=1@
PS=1@
FLASH=1@
PhaseCheck=1@


[SC8501C_SAMSUNG]
FDL=1@
FDL2=1@
NV=1@
BootLoader=1@
UserImg=1@
MMIRes=1@
MMICsc=0@
DSPCode=1@
OmadmFota=0@
Preload=0@
RomDisk=0@
FLASH=1@
EraseDU=1@
PhaseCheck=1@
KernelImg=1@

[SC8800H]
FDL=1@1
FDL2=1@1
NV=0@
BootLoader=0@
KernelImg=0@
KernelImg2=0@
UserImg=0@
MMIRes=0@
DSPCode=0@
OmadmFota=0@
Preload=0@
RomDisk=0@
FLASH=0@
EraseDU=0@
PhaseCheck=0@

[SC7701]
FDL=1@
FDL2=1@
NV=1@
BootLoader=1@
UserImg=1@
MMIRes=1@
DSPCode=1@
Preload=1@
FLASH=1@
PhaseCheck=1@
KernelImg=1@
EraseFS=1@

[SC9620_MGB_3500]
FDL=1@
FDL2=1@
NV=0@
NV_CA5=1@
BootLoader=1
DSP_PARM=0@
DSP_CA5=0@
DSP_LTE=1@
RomDisk=0@
FLASH=1@
FLASH_PARM=0@
PhaseCheck=1@
Kernel_PARM=0@
Kernel_CA5=1@
Kernel_SARM=0@
ARM7_DFS=1@
CMDLINE=0@

[SC9620_MGB_3131]
FDL=1@
FDL2=1@
NV=1@
NV_CA5=1@
BootLoader=1@
DSP_PARM=1@
DSP_CA5=0@
DSP_LTE=1@
RomDisk=0@
FLASH=1@
FLASH_CA5=1@
PhaseCheck=1@
Kernel_PARM=1@
Kernel_CA5=1@
Kernel_SARM=0@
ARM7_DFS=1@
CMDLINE=1@
[PAC_s9863a1h10]
FDL=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\fdl1-sign.bin
FDL2=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\fdl2-sign.bin
NV_LTE=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\sharkl3_pubcp_nvitem.bin
ProdNV=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\prodnv.img
PhaseCheck=1@
EraseUBOOT=1@
EraseUBOOTLOG=1@
SPLLoader=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\u-boot-spl-16k-sign.bin
VBMETA=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\vbmeta-sign.img
Modem_LTE=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\SC9600_sharkl3_pubcp_modem.dat
Modem_LTE_DELTANV=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\sharkl3_pubcp_deltanv.bin
DSP_LTE_LTE=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\sharkl3_pubcp_LTEA_DSP.bin
DSP_LTE_GGE=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\sharkl3_pubcp_DM_DSP.bin
DFS=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\sharkl3_cm4.bin
GPS_GL=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\gnssmodem.bin
GPS_BD=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\gnssbdmodem.bin
Modem_WCN=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\PM_sharkl3_cm4.bin
BOOT=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\boot.img
DTB=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\dtb.img
DTBO=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\dtbo.img
Recovery=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\recovery.img
System=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\system.img
UserData=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\userdata.img
BootLogo=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\LOGO.bmp
Fastboot_Logo=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\LOGO.bmp(1)
Cache=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\cache.img
FLASH_LTE=1@
EraseMisc=1@
Trustos=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\tos-sign.bin
SML=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\sml-sign.bin
Vendor=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\vendor.img
Product=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\product.img
Persist=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\persist.img
UBOOTLoader=1@E:\Tools\DFS\AK47\Download_tool\RESEARCHDOWNLOAD_R21.0.0001\ImageFiles\_DownloadFiles1313966000\u-boot-sign.bin
